# Generated by Django 5.1.3 on 2024-11-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
    ]
